import { UserProfile, VideoProject, GeneratedClip } from './types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_premium_789',
  name: 'Alex Vance',
  email: 'alex.creator@cliptor.io',
  tier: 'free', // Toggleable in settings for user to test both free and pro!
  creditsUsed: 1,
  creditsMax: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  joinedDate: 'Feb 2026',
};

export const INITIAL_CLIPS_PROJECT_1: GeneratedClip[] = [
  {
    id: 'clip_01_hook',
    projectId: 'proj_huberman_01',
    title: 'The 10-Minute Dopamine Reset Rule',
    summary: 'Dr. Huberman explains why checking your phone immediately after waking up damages your dopamine baseline for 24 hours.',
    hookSentence: '"If you touch your phone in the first 15 minutes of waking up, you literally prime your brain for anxiety."',
    viralScore: 97,
    hookScore: 98,
    flowScore: 94,
    durationSeconds: 42,
    aspectRatio: '9:16',
    thumbnail: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=600&auto=format&fit=crop&q=80',
    captionStyle: 'karaoke',
    transcriptExcerpt: 'If you touch your phone in the first 15 minutes of waking up, you literally prime your brain for anxiety. The photon intake from bright screens before sunlight resets your cortisol at the wrong circadian slope.',
    tags: ['neuroscience', 'dopamine', 'habits', 'focus'],
    startTime: 184,
    endTime: 226,
    publishedPlatforms: ['tiktok', 'youtube'],
    viewsEstimate: '420K - 1.2M',
  },
  {
    id: 'clip_02_humor',
    projectId: 'proj_huberman_01',
    title: 'Why 2 PM Coffee Ruins Deep Sleep',
    summary: 'A surprising breakdown of adenosine receptors and why caffeine has a 12-hour quarter life.',
    hookSentence: '"You think that 3 PM espresso gives you energy? It’s just borrowing anxiety from tomorrow."',
    viralScore: 93,
    hookScore: 95,
    flowScore: 90,
    durationSeconds: 38,
    aspectRatio: '9:16',
    thumbnail: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    captionStyle: 'cyberpunk',
    transcriptExcerpt: 'Adenosine builds pressure like a dam. Caffeine doesn’t drain the dam, it just hides the water level. The moment it wears off, the entire tidal wave hits you at 10 PM.',
    tags: ['coffee', 'sleep', 'productivity', 'health'],
    startTime: 610,
    endTime: 648,
    publishedPlatforms: ['instagram'],
    viewsEstimate: '250K - 700K',
  },
  {
    id: 'clip_03_insight',
    projectId: 'proj_huberman_01',
    title: 'The Physiological Sigh: Instant Calm in 2 Seconds',
    summary: 'The fastest science-backed protocol to drop heart rate and down-regulate sympathetic nervous system.',
    hookSentence: '"Two deep inhales through the nose, one long exhale through the mouth. Watch what happens."',
    viralScore: 91,
    hookScore: 89,
    flowScore: 93,
    durationSeconds: 51,
    aspectRatio: '9:16',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    captionStyle: 'minimal',
    transcriptExcerpt: 'Two deep inhales through the nose, one long exhale through the mouth. The second inhale pops open the collapsed alveoli in the lungs, dropping your heart rate within 3 heartbeats.',
    tags: ['stress', 'breathing', 'biohacking'],
    startTime: 1205,
    endTime: 1256,
    publishedPlatforms: [],
    viewsEstimate: '180K - 550K',
  },
];

export const INITIAL_CLIPS_PROJECT_2: GeneratedClip[] = [
  {
    id: 'clip_04_zuck',
    projectId: 'proj_zuck_02',
    title: 'Why Smart Glasses Replace Smartphones by 2030',
    summary: 'Mark Zuckerberg explains how holographic display waveguides and multimodal AI make pocket phones obsolete.',
    hookSentence: '"In 7 years, pulling a glowing glass slab out of your pocket will look as archaic as a pager."',
    viralScore: 99,
    hookScore: 99,
    flowScore: 96,
    durationSeconds: 35,
    aspectRatio: '9:16',
    thumbnail: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=600&auto=format&fit=crop&q=80',
    captionStyle: 'karaoke',
    transcriptExcerpt: 'In 7 years, pulling a glowing glass slab out of your pocket will look as archaic as a pager. When AI sees what you see and speaks into your ear via spatial audio, friction drops to zero.',
    tags: ['meta', 'ai', 'tech', 'future'],
    startTime: 430,
    endTime: 465,
    publishedPlatforms: ['tiktok', 'instagram', 'youtube'],
    viewsEstimate: '1.5M - 4.0M',
  },
  {
    id: 'clip_05_coding',
    projectId: 'proj_zuck_02',
    title: 'How 10x Engineers Will Work in 2026',
    summary: 'The shift from typing syntax to orchestrating autonomous agent swarms.',
    hookSentence: '"The best software engineers today aren’t writing loops anymore—they are reviewing agent diffs."',
    viralScore: 94,
    hookScore: 92,
    flowScore: 95,
    durationSeconds: 47,
    aspectRatio: '9:16',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    captionStyle: 'karaoke',
    transcriptExcerpt: 'The best software engineers today aren’t writing loops anymore—they are reviewing agent diffs. The leverage per developer went from 10x to 500x in less than 18 months.',
    tags: ['coding', 'software', 'startups', 'ai'],
    startTime: 890,
    endTime: 937,
    publishedPlatforms: ['youtube'],
    viewsEstimate: '600K - 1.8M',
  },
];

export const INITIAL_PROJECTS: VideoProject[] = [
  {
    id: 'proj_huberman_01',
    title: 'Huberman Lab #184: Science of Focus, Dopamine & High Performance',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=kPo3TfVfP1A',
    category: 'podcast',
    durationSeconds: 7420,
    status: 'completed',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
    createdAt: '2 hours ago',
    clipsCount: 3,
    clips: INITIAL_CLIPS_PROJECT_1,
  },
  {
    id: 'proj_zuck_02',
    title: 'Lex Fridman Podcast #418: Mark Zuckerberg on Meta AI, Orion Glasses & Future',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=Ff4fRgnuFgQ',
    category: 'interview',
    durationSeconds: 9840,
    status: 'completed',
    thumbnail: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=600&auto=format&fit=crop&q=80',
    createdAt: 'Yesterday',
    clipsCount: 2,
    clips: INITIAL_CLIPS_PROJECT_2,
  },
  {
    id: 'proj_allin_03',
    title: 'All-In Podcast E178: The $100B GPU Race & Next-Gen Autonomous Economy',
    sourceType: 'upload',
    fileName: 'all_in_e178_master_cut.mp4',
    category: 'podcast',
    durationSeconds: 4900,
    status: 'completed',
    thumbnail: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&auto=format&fit=crop&q=80',
    createdAt: '3 days ago',
    clipsCount: 4,
    clips: [],
  },
];
